apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-cicd-demo
  labels:
    app: secure-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-cicd-demo
  template:
    metadata:
      labels:
        app: secure-cicd-demo
    spec:
      containers:
        - name: secure-cicd-demo
          image: chaimachhiba/secure-cicd-demo:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
