apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secure-cicd-demo-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: secure-cicd-demo
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
